--[[
lvim is the global options object

Linters should be
filled in as strings with either
a global executable or a path to
an executable
]]
-- THESE ARE EXAMPLE CONFIGS FEEL FREE TO CHANGE TO WHATEVER YOU WANT

-- to disable icons and use a minimalist setup, uncomment the following
-- lvim.use_icons = false
-- lvim.keys.normal_mode["<S-l>"] = ":BufferLineCycleNext<CR>"
-- lvim.keys.normal_mode["<S-h>"] = ":BufferLineCyclePrev<CR>"
-- unmap a default keymapping
-- vim.keymap.del("n", "<C-Up>")
-- override a default keymapping
-- lvim.keys.normal_mode["<C-q>"] = ":q<cr>" -- or vim.keymap.set("n", "<C-q>", ":q<cr>" )
-- Change Telescope navigation to use j and k for navigation and n and p for history in both input and normal mode.
-- we use protected-mode (pcall) just in case the plugin wasn't loaded yet.
-- local _, actions = pcall(require, "telescope.actions")
-- lvim.builtin.telescope.defaults.mappings = {
--   -- for input mode
--   i = {
--     ["<C-j>"] = actions.move_selection_next,
--     ["<C-k>"] = actions.move_selection_previous,
--     ["<C-n>"] = actions.cycle_history_next,
--     ["<C-p>"] = actions.cycle_history_prev,
--   },
--   -- for normal mode
--   n = {
--     ["<C-j>"] = actions.move_selection_next,
--     ["<C-k>"] = actions.move_selection_previous,
--   },
-- }

-- Use which-key to add extra bindings with the leader-key prefix
-- lvim.builtin.which_key.mappings["P"] = { "<cmd>Telescope projects<CR>", "Projects" }
-- lvim.builtin.which_key.mappings["t"] = {
--   name = "+Trouble",
--   r = { "<cmd>Trouble lsp_references<cr>", "References" },
--   f = { "<cmd>Trouble lsp_definitions<cr>", "Definitions" },
--   d = { "<cmd>Trouble document_diagnostics<cr>", "Diagnostics" },
--   q = { "<cmd>Trouble quickfix<cr>", "QuickFix" },
--   l = { "<cmd>Trouble loclist<cr>", "LocationList" },
--   w = { "<cmd>Trouble workspace_diagnostics<cr>", "Workspace Diagnostics" },
-- }
-- lvim.builtin.which_key.mappings["x"] = { "<cmd> lua require'hop'.hint_words({ hint_position = require'hop.hint'.HintPosition.END })<cr>", "Hop to word" }
-- vim.api.nvim_set_keymap('n', '<leader>x', "<cmd> lua require'hop'.hint_words({ hint_position = require'hop.hint'.HintPosition.END })<cr>", {})
-- vim.api.nvim_set_keymap('v', '<leader>x', "<cmd> lua require'hop'.hint_words({ hint_position = require'hop.hint'.HintPosition.END })<cr>", {})
-- vim.api.nvim_set_keymap('o', '<leader>x', "<cmd> lua require'hop'.hint_words({ hint_position = require'hop.hint'.HintPosition.END, inclusive_jump = true })<cr>", {})
-- lvim.builtin.telescope.defaults.layout_config.horizontal.preview_width = 50
-- lvim.builtin.telescope.defaults.layout_config
-- generic LSP settings

-- -- make sure server will always be installed even if the server is in skipped_servers list
-- lvim.lsp.installer.setup.ensure_installed = {
--     "sumeko_lua",
--     "jsonls",
-- }
-- -- change UI setting of `LspInstallInfo`
-- -- see <https://github.com/williamboman/nvim-lsp-installer#default-configuration>
-- lvim.lsp.installer.setup.ui.check_outdated_servers_on_open = false
-- lvim.lsp.installer.setup.ui.border = "rounded"
-- lvim.lsp.installer.setup.ui.keymaps = {
--     uninstall_server = "d",
--     toggle_server_expand = "o",
-- }

-- ---@usage disable automatic installation of servers
-- lvim.lsp.installer.setup.automatic_installation = false

-- ---configure a server manually. !!Requires `:LvimCacheReset` to take effect!!
-- ---see the full default list `:lua print(vim.inspect(lvim.lsp.automatic_configuration.skipped_servers))`
-- vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pyright" })
-- local opts = {} -- check the lspconfig documentation for a list of all possible options
-- require("lvim.lsp.manager").setup("pyright", opts)
-- opts = {} -- check the lspconfig documentation for a list of all possible options
-- require("lvim.lsp.manager").setup("pyright", opts)



-- ---remove a server from the skipped list, e.g. eslint, or emmet_ls. !!Requires `:LvimCacheReset` to take effect!!
-- ---`:LvimInfo` lists which server(s) are skipped for the current filetype
-- lvim.lsp.automatic_configuration.skipped_servers = vim.tbl_filter(function(server)
--   return server ~= "emmet_ls"
-- end, lvim.lsp.automatic_configuration.skipped_servers)

-- -- you can set a custom on_attach function that will be used for all the language servers
-- -- See <https://github.com/neovim/nvim-lspconfig#keybindings-and-completion>
-- lvim.lsp.on_attach_callback = function(client, bufnr)
--   local function buf_set_option(...)
--     vim.api.nvim_buf_set_option(bufnr, ...)
--   end
--   --Enable completion triggered by <c-x><c-o>
--   buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")
-- end
--   {
--     -- each formatter accepts a list of options identical to https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#Configuration
--     command = "prettier",
--     ---@usage arguments to pass to the formatter
--     -- these cannot contain whitespaces, options such as `--line-width 80` become either `{'--line-width', '80'}` or `{'--line-width=80'}`
--     extra_args = { "--print-with", "100" },
--     ---@usage specify which filetypes to enable. By default a providers will attach to all the filetypes it supports.
--     filetypes = { "typescript", "typescriptreact" },
--   },
-- }

-- -- set additional linters
-- local linters = require "lvim.lsp.null-ls.linters"
-- linters.setup {
--   { command = "flake8", filetypes = { "python" } },
--   {
--     -- each linter accepts a list of options identical to https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#Configuration
--     command = "shellcheck",
--     ---@usage arguments to pass to the formatter
--     -- these cannot contain whitespaces, options such as `--line-width 80` become either `{'--line-width', '80'}` or `{'--line-width=80'}`
--     extra_args = { "--severity", "warning" },
--   },
--   {
--     command = "codespell",
--     ---@usage specify which filetypes to enable. By default a providers will attach to all the filetypes it supports.
--     filetypes = { "javascript", "python" },
--   },
-- }
-- vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, {
--   "rust_analyzer",
-- })

-- Additional Plugins
lvim.plugins = {
  -- {"tpope/vim-vinegar"},
  -- vim-fetch makes vim accept line and column numbers when openning files
  -- { dir = '~/dev/vim-fetch' },
  -- { 'sindrets/diffview.nvim', event = "BufRead" },

  -- # MOTION

  -- {
  --   "phaazon/hop.nvim",
  --   event = "BufRead",
  --   config = function()
  --     local hop = require("hop")
  --     hop.setup()
  --     vim.api.nvim_set_keymap("n", "s", ":HopChar2<cr>", { silent = true })
  --     vim.api.nvim_set_keymap("n", "S", ":HopWord<cr>", { silent = true })
  --     vim.keymap.set('o', ',', hop.hint_char1)
  --   end,
  -- },
  -- {
  --   'rmagatti/auto-session',
  --   config = function()
  --     require("auto-session").setup {
  --       log_level = "error",
  --       pre_save_cmds = { "NvimTreeClose" },
  --       auto_session_suppress_dirs = { "~/", "~/Downloads", "/" },
  --     }
  --   end
  -- },
  -- {
  --   'tzachar/cmp-tabnine',
  --   run = './install.sh',
  --   dependencies = 'hrsh7th/nvim-cmp',
  -- },
  -- { dir = '~/dev/vim-floaterm' },
  -- {
  --   "zbirenbaum/copilot.lua",
  --   event = { "VimEnter" },
  --   config = function()
  --     vim.defer_fn(function()
  --       require("copilot").setup {
  --         plugin_manager_path = get_runtime_dir() .. "/site/pack/packer",
  --         auto_refresh = true,
  --       }
  --     end, 100)
  --   end,
  -- },
  -- {
  --   "zbirenbaum/copilot-cmp",
  --   after = { "copilot.lua", "nvim-cmp" },
  -- },
  -- {
  --   'github/copilot.vim'
  -- },
  -- { 'skyuplam/broot.nvim' },
  -- { 'rbgrouleff/bclose.vim' },
  -- {
  --   'sidebar-nvim/sidebar.nvim',
  --   config = function()
  --     local sidebar = require("sidebar-nvim")
  --     local opts = { open = true }
  --     sidebar.setup({
  --       open = true,
  --       sections = { "buffers" },
  --       buffers = {
  --         icon = "",
  --         ignored_buffers = {}, -- ignore buffers by regex
  --         sorting = "id", -- alternatively set it to "name" to sort by buffer name instead of buf id
  --         show_numbers = true, -- whether to also show the buffer numbers
  --         ignore_not_loaded = false, -- whether to ignore not loaded buffers
  --         ignore_terminal = true, -- whether to show terminal buffers in the list
  --       }
  --     })
  --   end
  -- },
  -- {
  --   "simrat39/rust-tools.nvim",
  --   config = function()
  --     -- vim.cmd [[
  --     --   echomsg 'config rust_tools'
  --     -- ]]
  --     -- print("config rust_tools")
  --     require("user.rust_tools").config()
  --     require('rust-tools').setup({
  --         server = {
  --           on_attach = function(_, bufnr)
  --             local rt = require('rust-tools')
  --             -- Hover actions
  --             vim.keymap.set("n", "<Leader>lh", rt.hover_actions.hover_actions, { buffer = bufnr })
  --             -- Code action groups
  --             vim.keymap.set("n", "<Leader>lg", rt.code_action_group.code_action_group, { buffer = bufnr })
  --             local mappings = {
  --                 ["K"] = { "<cmd>lua vim.lsp.buf.hover()<cr>", "Show hover" },
  --                 ["gd"] = { "<cmd>lua vim.lsp.buf.definition()<cr>", "Goto definition" },
  --                 ["gD"] = { "<cmd>lua vim.lsp.buf.declaration()<cr>", "Goto Declaration" },
  --                 ["gr"] = { "<cmd>lua vim.lsp.buf.references()<cr>", "Goto references" },
  --                 ["gI"] = { "<cmd>lua vim.lsp.buf.implementation()<cr>", "Goto Implementation" },
  --                 ["gs"] = { "<cmd>lua vim.lsp.buf.signature_help()<cr>", "show signature help" },
  --                 ["gl"] = {
  --                   function()
  --                     local float = vim.diagnostic.config().float
  --                     if float then
  --                       local config = type(float) == "table" and float or {}
  --                       config.scope = "line"
  --                       vim.diagnostic.open_float(config)
  --                     end
  --                   end,
  --                   "Show line diagnostics",
  --                 },
  --           }
  --           local wk = require("which-key")
  --           wk.register(mappings, {buffer = bufnr})
  --           end,
  --         },
  --         tools = {
  --             -- how to execute terminal commands
  --             -- options right now: termopen / quickfix / toggleterm / vimux
  --             -- executor = require("rust-tools.executors").toggleterm,
  --             rustfmt = {
  --                 -- Set to true to pass '--check' to rustfmt
  --                 check = true,
  --                 -- Set to true to pass '--edition=2021' to rustfmt
  --                 edition = '2021',
  --                 -- List of custom flags to pass to rustfmt
  --                 extra_args = {"+nightly"}
  --             },
  --         }
  --     })
  --   end,
  --   ft = { "rust", "rs" },
  -- },
  -- {
  --   "rcarriga/nvim-dap-ui",
  --   config = function()
  --     require("user.dapui").config()
  --   end,
  --   ft = { "python", "rust", "go" },
  --   event = "BufReadPost",
  --   dependencies = { "mfussenegger/nvim-dap" },
  --   disable = not lvim.builtin.dap.active,
  -- },
  -- {
  --   "~/dev/rust-doc.vim",
  --   config = function()
  --     require("user.rust_doc").config()
  --   end,
  --   ft = { "rust" },
  -- }
}

-- lvim.plugins = {
--     {"folke/tokyonight.nvim"},
--     {
--       "folke/trouble.nvim",
--       cmd = "TroubleToggle",
--     },
-- }

-- Autocommands (https://neovim.io/doc/user/autocmd.html)
-- vim.api.nvim_create_autocmd("BufEnter", {
--   pattern = { "*.json", "*.jsonc" },
--   -- enable wrap mode for json files only
--   command = "setlocal wrap",
-- })
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "zsh",
--   callback = function()
--     -- let treesitter use bash highlight for zsh files as well
--     require("nvim-treesitter.highlight").attach(0, "bash")
--   end,
-- })
-- lvim.builtin.which_key.mappings["ds"] = {
--   "<cmd>lua if vim.bo.filetype == 'rust' then vim.cmd[[RustDebuggables]] else require'dap'.continue() end<CR>",
--   "Start",
-- }

-- dap.adapters.codelldb = {
--   type = 'server',
--   host = '127.0.0.1',
--   port = 13000 -- 💀 Use the port printed out or specified with `--port`
-- }

-- vim.cmd [[
-- function! SynStack()
--   if !exists("*synstack")
--     return
--   endif
--   echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
-- endfunc
-- function! SynGroup()
--     let l:s = synID(line('.'), col('.'), 1)
--     echo synIDattr(l:s, 'name') . ' -> ' . synIDattr(synIDtrans(l:s), 'name')
-- endfun
-- ]]
-- lvim.builtin.which_key.mappings["c"] = {
--   c = { "<cmd>call SynStack()<CR>", "View highlight stack" },
--   g = { "<cmd>call SynGroup()<CR>", "View highlight stack" },
-- }
-- vim.cmd [[
-- " Show the syntax highlight group under cursor
-- nnoremap <F10> <cmd>echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
--     \ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
--     \ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<cr>
-- ]]
